name: Deploy a new version

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]

    steps:
      - name: "Actions checkout"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update version in package.json
        uses: maks-stupak/gh-action-bump-version@v7.1.5

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1

      - name: Build a project
        uses: npm run build --if-present
